---
kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: git

steps:
  - name: build
    image: docker
    privileged: true
    environment: 
      TOKEN:
        from_secret: registry_token
    commands:
      - dockerd &
      - docker login -u registry -p $TOKEN registry.v0l.io
      - docker build -t registry.v0l.io/zap-stream-api:latest -f NostrStreamer/Dockerfile .
      - docker push registry.v0l.io/zap-stream-api:latest
      - kill $(cat /var/run/docker.pid)
