---
kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: git

steps:
  - name: build
    image: r.j3ss.co/img
    privileged: true
    environment: 
      TOKEN:
        from_secret: registry_token
    commands:
      - img login -u registry -p $TOKEN registry.v0l.io
      - img build -t registry.v0l.io/zap-stream-api:latest -f NostrStreamer/Dockerfile .
      - img push registry.v0l.io/zap-stream-api:latest
