volumes:
  minio-dvr:
services:
  srs-origin:
    image: ossrs/srs:5
    volumes:
      - "./docker/srs-origin.conf:/usr/local/srs/conf/docker.conf"
    ports:
      - "9001:1935"
      - "9002:1985"
      - "9003:8080"
      - "9004:8000"
  srs-edge:
    image: ossrs/srs:5
    volumes:
      - "./docker/srs-edge.conf:/usr/local/srs/conf/docker.conf"
    ports:
      - "9005:1935"
      - "1985:1985"
      - "9007:8080"
      - "9008:8000"
  nostr:
    image: scsibug/nostr-rs-relay
    ports:
      - "8081:8080"
  postgres:
    image: postgres:15
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - "5431:5432"
  minio:
    image: quay.io/minio/minio
    command:
      - "server"
      - "/data" 
      - "--console-address"
      - ":9001"
    environment:
      - "MINIO_SERVER_URL=http://localhost:9010"
    ports:
      - "9010:9000"
      - "9011:9001"
    volumes:
      - "minio-dvr:/data"
  redis:
    image: redis
    ports:
      - "6666:6379"